### ISSUE TITLE
Adopt a Code Style

### ISSUE THREAD

**Issue by thepabloaguilar** [globocom/auror-core#12]
Will be good adopt a Code Style to the project, but it's so hard to maintaining it across many changes & PR's, my suggestion is to adopt a formatter/linter.

We can use these:
* [autopep8](https://github.com/hhatto/autopep8) (already in project)
* [black](https://github.com/psf/black)
* [yapf](https://github.com/google/yapf)

And we can add a step to verify if style was applied in Travis CI.

**Comment by dmvieira** [comment]
Agree with autopep8
