### ISSUE TITLE
Read flow v2 from files to Python memory

### ISSUE THREAD

**Issue by dmvieira** [globocom/auror-core#5]
Reading flow files and write Python code should be useful for Auror adoption.

It should just read yaml files and load to memory

**Comment by thepabloaguilar** [comment]
Hey, I want to take this issue. Is it like `Env` class??

**Comment by dmvieira** [comment]
Hey! No, it's like load an yaml configuration file to correct Python classes. There are class for params and for commands. We need the ability to read these yaml files and produce Auror python code. There's a great readme for that: https://github.com/azkaban/azkaban/wiki/Azkaban-Flow-2.0-Design

Perhaps it's easy to write Python code from flow v1 instead of flow v2 on this issue: https://github.com/globocom/auror-core/issues/4 because it's only a properties file

**Comment by thepabloaguilar** [comment]
So, you want something like this:

```python
from auror_core.v2.loaders import YamlLoader

flows = YamlLoader('path/to/yaml/file')
```

`flows` receive a list of flows inside the file, or you can export the flows inside YAML File as a Python File?

**Comment by dmvieira** [comment]
Both. You should load flows and then export as Python file. Do you need 2 issues?

**Comment by dmvieira** [comment]
Here https://github.com/globocom/auror-core/issues/8 I did a new one. So, this issue is just load to memory

**Comment by thepabloaguilar** [comment]
@dmvieira I've made the inital implementation, you can confirm if is that ideia, please? The PR is #9

**Comment by dmvieira** [comment]
Yeah! It's perfect!!
